# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import exemplo_pb2 as exemplo__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in exemplo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CalculadoraStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Somar = channel.unary_unary(
                '/calculadora.Calculadora/Somar',
                request_serializer=exemplo__pb2.DoisNumeros.SerializeToString,
                response_deserializer=exemplo__pb2.Resultado.FromString,
                _registered_method=True)
        self.Subtrair = channel.unary_unary(
                '/calculadora.Calculadora/Subtrair',
                request_serializer=exemplo__pb2.DoisNumeros.SerializeToString,
                response_deserializer=exemplo__pb2.Resultado.FromString,
                _registered_method=True)
        self.Multiplicar = channel.unary_unary(
                '/calculadora.Calculadora/Multiplicar',
                request_serializer=exemplo__pb2.DoisNumeros.SerializeToString,
                response_deserializer=exemplo__pb2.Resultado.FromString,
                _registered_method=True)
        self.Dividir = channel.unary_unary(
                '/calculadora.Calculadora/Dividir',
                request_serializer=exemplo__pb2.DoisNumeros.SerializeToString,
                response_deserializer=exemplo__pb2.Resultado.FromString,
                _registered_method=True)
        self.CalcularPotencia = channel.unary_unary(
                '/calculadora.Calculadora/CalcularPotencia',
                request_serializer=exemplo__pb2.DoisNumeros.SerializeToString,
                response_deserializer=exemplo__pb2.Resultado.FromString,
                _registered_method=True)
        self.CalcularRaizQuadrada = channel.unary_unary(
                '/calculadora.Calculadora/CalcularRaizQuadrada',
                request_serializer=exemplo__pb2.Numero.SerializeToString,
                response_deserializer=exemplo__pb2.Resultado.FromString,
                _registered_method=True)
        self.SomarStream = channel.stream_unary(
                '/calculadora.Calculadora/SomarStream',
                request_serializer=exemplo__pb2.Numero.SerializeToString,
                response_deserializer=exemplo__pb2.Resultado.FromString,
                _registered_method=True)
        self.GerarTabuada = channel.unary_stream(
                '/calculadora.Calculadora/GerarTabuada',
                request_serializer=exemplo__pb2.Numero.SerializeToString,
                response_deserializer=exemplo__pb2.Resultado.FromString,
                _registered_method=True)
        self.CalcularMediaMovel = channel.stream_stream(
                '/calculadora.Calculadora/CalcularMediaMovel',
                request_serializer=exemplo__pb2.Numero.SerializeToString,
                response_deserializer=exemplo__pb2.Resultado.FromString,
                _registered_method=True)


class CalculadoraServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Somar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subtrair(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Multiplicar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Dividir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalcularPotencia(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalcularRaizQuadrada(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SomarStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GerarTabuada(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalcularMediaMovel(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculadoraServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Somar': grpc.unary_unary_rpc_method_handler(
                    servicer.Somar,
                    request_deserializer=exemplo__pb2.DoisNumeros.FromString,
                    response_serializer=exemplo__pb2.Resultado.SerializeToString,
            ),
            'Subtrair': grpc.unary_unary_rpc_method_handler(
                    servicer.Subtrair,
                    request_deserializer=exemplo__pb2.DoisNumeros.FromString,
                    response_serializer=exemplo__pb2.Resultado.SerializeToString,
            ),
            'Multiplicar': grpc.unary_unary_rpc_method_handler(
                    servicer.Multiplicar,
                    request_deserializer=exemplo__pb2.DoisNumeros.FromString,
                    response_serializer=exemplo__pb2.Resultado.SerializeToString,
            ),
            'Dividir': grpc.unary_unary_rpc_method_handler(
                    servicer.Dividir,
                    request_deserializer=exemplo__pb2.DoisNumeros.FromString,
                    response_serializer=exemplo__pb2.Resultado.SerializeToString,
            ),
            'CalcularPotencia': grpc.unary_unary_rpc_method_handler(
                    servicer.CalcularPotencia,
                    request_deserializer=exemplo__pb2.DoisNumeros.FromString,
                    response_serializer=exemplo__pb2.Resultado.SerializeToString,
            ),
            'CalcularRaizQuadrada': grpc.unary_unary_rpc_method_handler(
                    servicer.CalcularRaizQuadrada,
                    request_deserializer=exemplo__pb2.Numero.FromString,
                    response_serializer=exemplo__pb2.Resultado.SerializeToString,
            ),
            'SomarStream': grpc.stream_unary_rpc_method_handler(
                    servicer.SomarStream,
                    request_deserializer=exemplo__pb2.Numero.FromString,
                    response_serializer=exemplo__pb2.Resultado.SerializeToString,
            ),
            'GerarTabuada': grpc.unary_stream_rpc_method_handler(
                    servicer.GerarTabuada,
                    request_deserializer=exemplo__pb2.Numero.FromString,
                    response_serializer=exemplo__pb2.Resultado.SerializeToString,
            ),
            'CalcularMediaMovel': grpc.stream_stream_rpc_method_handler(
                    servicer.CalcularMediaMovel,
                    request_deserializer=exemplo__pb2.Numero.FromString,
                    response_serializer=exemplo__pb2.Resultado.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculadora.Calculadora', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('calculadora.Calculadora', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Calculadora(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Somar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculadora.Calculadora/Somar',
            exemplo__pb2.DoisNumeros.SerializeToString,
            exemplo__pb2.Resultado.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subtrair(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculadora.Calculadora/Subtrair',
            exemplo__pb2.DoisNumeros.SerializeToString,
            exemplo__pb2.Resultado.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Multiplicar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculadora.Calculadora/Multiplicar',
            exemplo__pb2.DoisNumeros.SerializeToString,
            exemplo__pb2.Resultado.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Dividir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculadora.Calculadora/Dividir',
            exemplo__pb2.DoisNumeros.SerializeToString,
            exemplo__pb2.Resultado.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalcularPotencia(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculadora.Calculadora/CalcularPotencia',
            exemplo__pb2.DoisNumeros.SerializeToString,
            exemplo__pb2.Resultado.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalcularRaizQuadrada(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculadora.Calculadora/CalcularRaizQuadrada',
            exemplo__pb2.Numero.SerializeToString,
            exemplo__pb2.Resultado.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SomarStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/calculadora.Calculadora/SomarStream',
            exemplo__pb2.Numero.SerializeToString,
            exemplo__pb2.Resultado.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GerarTabuada(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/calculadora.Calculadora/GerarTabuada',
            exemplo__pb2.Numero.SerializeToString,
            exemplo__pb2.Resultado.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalcularMediaMovel(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/calculadora.Calculadora/CalcularMediaMovel',
            exemplo__pb2.Numero.SerializeToString,
            exemplo__pb2.Resultado.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
