# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: exemplo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'exemplo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexemplo.proto\x12\x0b\x63\x61lculadora\"/\n\x0b\x44oisNumeros\x12\x0f\n\x07numero1\x18\x01 \x01(\x01\x12\x0f\n\x07numero2\x18\x02 \x01(\x01\"\x17\n\x06Numero\x12\r\n\x05valor\x18\x01 \x01(\x01\"0\n\tResultado\x12\x11\n\tresultado\x18\x01 \x01(\x01\x12\x10\n\x08mensagem\x18\x02 \x01(\t2\xd3\x04\n\x0b\x43\x61lculadora\x12\x39\n\x05Somar\x12\x18.calculadora.DoisNumeros\x1a\x16.calculadora.Resultado\x12<\n\x08Subtrair\x12\x18.calculadora.DoisNumeros\x1a\x16.calculadora.Resultado\x12?\n\x0bMultiplicar\x12\x18.calculadora.DoisNumeros\x1a\x16.calculadora.Resultado\x12;\n\x07\x44ividir\x12\x18.calculadora.DoisNumeros\x1a\x16.calculadora.Resultado\x12\x44\n\x10\x43\x61lcularPotencia\x12\x18.calculadora.DoisNumeros\x1a\x16.calculadora.Resultado\x12\x43\n\x14\x43\x61lcularRaizQuadrada\x12\x13.calculadora.Numero\x1a\x16.calculadora.Resultado\x12<\n\x0bSomarStream\x12\x13.calculadora.Numero\x1a\x16.calculadora.Resultado(\x01\x12=\n\x0cGerarTabuada\x12\x13.calculadora.Numero\x1a\x16.calculadora.Resultado0\x01\x12\x45\n\x12\x43\x61lcularMediaMovel\x12\x13.calculadora.Numero\x1a\x16.calculadora.Resultado(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'exemplo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DOISNUMEROS']._serialized_start=30
  _globals['_DOISNUMEROS']._serialized_end=77
  _globals['_NUMERO']._serialized_start=79
  _globals['_NUMERO']._serialized_end=102
  _globals['_RESULTADO']._serialized_start=104
  _globals['_RESULTADO']._serialized_end=152
  _globals['_CALCULADORA']._serialized_start=155
  _globals['_CALCULADORA']._serialized_end=750
# @@protoc_insertion_point(module_scope)
